# Generated by Django 5.1.4 on 2026-04-03 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectabilitySurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal', models.DateField()),
                ('elektabilitas_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sumber', models.CharField(max_length=200)),
                ('catatan', models.TextField(blank=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electability_surveys', to='accounts.tenant')),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
    ]
