# Generated by Django 5.1.4 on 2026-06-28 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_collapse_roles_to_four'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('suspend', 'Suspend tenant'), ('activate', 'Activate tenant'), ('publish', 'Publish candidate'), ('pause', 'Pause candidate'), ('provision', 'Provision candidate'), ('impersonate', 'Impersonate candidate'), ('create_admin', 'Create staff user')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_actions', to=settings.AUTH_USER_MODEL)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.tenant')),
            ],
            options={
                'db_table': 'platform_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
