# Generated by Django 5.1.4 on 2026-04-01 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('clicks', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-clicks'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='teams.referrallink')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(choices=[(1, 'Koordinator Wilayah'), (2, 'Koordinator Kecamatan'), (3, 'Koordinator Kelurahan'), (4, 'Relawan')], default=4)),
                ('nama', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('wilayah_name', models.CharField(max_length=200)),
                ('wilayah_level', models.CharField(choices=[('provinsi', 'Provinsi'), ('kabupaten', 'Kabupaten/Kota'), ('kecamatan', 'Kecamatan'), ('kelurahan', 'Kelurahan')], default='kelurahan', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='teams.teammember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='referrallink',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='teams.teammember'),
        ),
    ]
