# Generated by Django 5.1.4 on 2026-04-06 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
        ('teams', '0002_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=300)),
                ('isi', models.TextField()),
                ('min_level', models.IntegerField(choices=[(0, 'Semua'), (1, 'Koordinator Wilayah ke atas'), (2, 'Koordinator Kecamatan ke atas'), (3, 'Koordinator Kelurahan ke atas'), (4, 'Semua termasuk Relawan')], default=4, help_text='Members at this level and above will see this announcement.')),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
