# Generated by Django 5.1.4 on 2026-04-08 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode'),
        ('teams', '0003_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='is_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='kategori',
            field=models.CharField(blank=True, choices=[('sosialisasi', 'Sosialisasi'), ('pembagian_materi', 'Pembagian Materi'), ('pendataan', 'Pendataan'), ('event', 'Event'), ('digital', 'Digital')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='poin_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teams.teammember'),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='teams.teammember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('register', 'Registrasi Relawan'), ('task_complete', 'Selesai Tugas'), ('share_content', 'Bagikan Konten'), ('manual_supporter', 'Input Pendukung Manual'), ('link_supporter', 'Pendukung via Link'), ('event_checkin', 'Checkin Event')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_rules', to='accounts.tenant')),
            ],
            options={
                'ordering': ['action_type'],
                'unique_together': {('tenant', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'Dikerjakan'), ('completed', 'Selesai'), ('expired', 'Kedaluwarsa'), ('rejected', 'Ditolak')], default='in_progress', max_length=20)),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='tasks/evidence/')),
                ('evidence_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teams.task')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='teams.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('task', 'volunteer')},
            },
        ),
    ]
