# Generated by Django 5.1.4 on 2026-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_task_capacity_task_is_pool_task_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='alasan_bergabung',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='source',
            field=models.CharField(choices=[('manual_add', 'Ditambah Admin'), ('self_registration', 'Registrasi Mandiri')], default='manual_add', max_length=30),
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('active', 'Aktif'), ('rejected', 'Ditolak'), ('inactive', 'Nonaktif')], default='active', max_length=20),
        ),
    ]
