# Generated by Django 5.1.4 on 2026-04-03 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=300)),
                ('media_type', models.CharField(choices=[('image', 'Gambar'), ('video', 'Video'), ('caption', 'Caption Saja')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='creatives/')),
                ('caption', models.TextField(blank=True)),
                ('tema', models.CharField(choices=[('infrastruktur', 'Infrastruktur'), ('kesehatan', 'Kesehatan'), ('pendidikan', 'Pendidikan'), ('ekonomi', 'Ekonomi'), ('lingkungan', 'Lingkungan'), ('profil', 'Profil Kandidat'), ('event', 'Event'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('platform_tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_creatives', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=300)),
                ('caption', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('meta_ads', 'Meta Ads'), ('tiktok_ads', 'TikTok Ads')], max_length=20)),
                ('jenis', models.CharField(choices=[('post', 'Post'), ('story', 'Story'), ('reel', 'Reel / Short'), ('ads', 'Iklan'), ('live', 'Live')], default='post', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Terjadwal'), ('published', 'Tayang'), ('cancelled', 'Dibatalkan')], default='draft', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='content.adcreative')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='accounts.tenant')),
            ],
            options={
                'ordering': ['scheduled_at', '-created_at'],
            },
        ),
    ]
