# Generated by Django 5.1.4 on 2026-04-08 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode'),
        ('content', '0001_initial'),
        ('teams', '0004_task_capacity_task_is_pool_task_kategori_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='is_daily_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='reward_max_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='reward_per_100_views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('body', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('category', models.CharField(choices=[('kegiatan', 'Kegiatan'), ('program', 'Program'), ('pengumuman', 'Pengumuman'), ('media', 'Media')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasikan')], default='draft', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('proof_url', models.URLField(blank=True)),
                ('proof_screenshot', models.ImageField(blank=True, null=True, upload_to='content/proofs/')),
                ('view_count', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('last_updated_views_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content.contentitem')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_shares', to='teams.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('content', 'volunteer')},
            },
        ),
    ]
