# Generated by Django 5.1.4 on 2026-04-03 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('pesan', models.TextField()),
                ('tema', models.CharField(choices=[('infrastruktur', 'Infrastruktur'), ('kesehatan', 'Kesehatan'), ('pendidikan', 'Pendidikan'), ('ekonomi', 'Ekonomi'), ('lingkungan', 'Lingkungan'), ('sosial', 'Sosial'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('wilayah', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('unread', 'Belum Dibaca'), ('read', 'Sudah Dibaca'), ('replied', 'Sudah Dibalas')], default='unread', max_length=20)),
                ('balasan_publik', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirasi_list', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pertanyaan', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Aktif'), ('closed', 'Ditutup')], default='draft', max_length=10)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teks', models.CharField(max_length=300)),
                ('vote_count', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='engagement.poll')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.poll')),
            ],
            options={
                'unique_together': {('poll', 'ip_hash')},
            },
        ),
    ]
