# Generated by Django 5.1.4 on 2026-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirasi',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aspirasi',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirasi',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
