# Generated by Django 5.1.4 on 2026-04-06 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
        ('teams', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=300)),
                ('deskripsi', models.TextField(blank=True)),
                ('lokasi', models.CharField(blank=True, max_length=300)),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasikan'), ('ongoing', 'Sedang Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=15)),
                ('target_peserta', models.IntegerField(default=0)),
                ('live_url', models.CharField(blank=True, max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(max_length=64, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='teams.teammember')),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'unique_together': {('event', 'team_member')},
            },
        ),
    ]
