# Generated by Django 5.1.4 on 2026-04-02 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok'), ('google', 'Google')], max_length=20)),
                ('account_id', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_accounts', to='accounts.tenant')),
            ],
            options={
                'ordering': ['platform', 'account_name'],
                'unique_together': {('tenant', 'platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('allocations', models.JSONField(default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('alert_threshold_pct', models.IntegerField(default=80)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AdsCampaignSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=20)),
                ('campaign_id', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=300)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('reach', models.BigIntegerField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('snapshot_date', models.DateField()),
                ('raw_data', models.JSONField(default=dict)),
                ('ads_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ads.adsaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_snapshots', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-snapshot_date', '-spend'],
                'unique_together': {('ads_account', 'campaign_id', 'snapshot_date')},
            },
        ),
    ]
