# Generated by Django 5.1.4 on 2026-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adsauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
