# Generated by Django 5.1.4 on 2026-04-01 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='candidates/photos/')),
                ('nomor_urut', models.IntegerField(blank=True, null=True)),
                ('jenis_pemilihan', models.CharField(choices=[('pileg_dpr', 'Pileg DPR'), ('pileg_dprd_provinsi', 'Pileg DPRD Provinsi'), ('pileg_dprd_kota', 'Pileg DPRD Kota/Kabupaten'), ('pilkada_bupati', 'Pilkada Bupati'), ('pilkada_walikota', 'Pilkada Walikota'), ('pilkada_gubernur', 'Pilkada Gubernur')], default='pileg_dprd_kota', max_length=30)),
                ('dapil', models.CharField(blank=True, max_length=200)),
                ('partai', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('visi', models.TextField(blank=True)),
                ('misi', models.JSONField(default=list)),
                ('program_unggulan', models.JSONField(default=list)),
                ('sosmed', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused')], default='draft', max_length=10)),
                ('color_primary', models.CharField(default='#1E40AF', max_length=7)),
                ('color_secondary', models.CharField(default='#FFFFFF', max_length=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='accounts.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates_candidate',
            },
        ),
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='candidates/hero/')),
                ('hero_video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('sections_order', models.JSONField(default=list)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='candidates/og/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_page', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidates_campaignpage',
            },
        ),
    ]
