# Generated by Django 5.1.4 on 2026-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='foto_external',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='foto_sampul_external',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='galeri',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tanggal_pemilihan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
