# Generated by Django 5.1.4 on 2026-04-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_phone_user_referral_code_user_role_and_more'),
        ('supporters', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='referred_by_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporters', to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='accounts.tenant'),
        ),
    ]
