# Generated by Django 5.1.4 on 2026-04-06 02:17

import django.db.models.deletion
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    import secrets
    Supporter = apps.get_model('supporters', 'Supporter')
    for s in Supporter.objects.filter(referral_code=''):
        s.referral_code = secrets.token_urlsafe(8)
        s.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0002_initial'),
    ]

    operations = [
        # Add referral_code WITHOUT unique constraint first
        migrations.AddField(
            model_name='supporter',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporter',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supporter',
            name='referred_by_supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='supporters.supporter'),
        ),
        # Backfill unique codes for existing rows
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='supporter',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
