# Generated by Django 5.1.4 on 2026-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0003_supporter_referral_code_supporter_referral_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='source',
            field=models.CharField(choices=[('self_registration', 'Registrasi Mandiri'), ('manual_entry', 'Input Manual oleh Relawan'), ('referral_link', 'Via Link Referral')], default='self_registration', max_length=30),
        ),
    ]
