# Generated by Django 5.1.4 on 2026-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agency_tenant_agency_user_agency_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='relawan_auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
